### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by edfloreshz** [comment]
Thanks! Would you like to add your name and email to `translator-credits` or leave it as is?

**Comment by albanobattistella** [comment]
> Thanks! Would you like to add your name and email to `translator-credits` or leave it as is?

Hi,
yes please!

**Comment by edfloreshz** [comment]
Awesome! Let me know when you do to merge this.

**Comment by albanobattistella** [comment]
> Awesome! Let me know when you do to merge this.

you can merge now!

**Pull request merged**
